### PR TITLE
Update FindVcvars and drop git protocol usage

### PR DESCRIPTION
**Pull request by jamesobutler**
A follow-up to https://github.com/PlusToolkit/PlusBuild/pull/82 with a set of various small updates.

### CODE REVIEW

**Comment by jamesobutler** [comment]
cc: @Sunderlandkyl or @adamrankin for review

**Review by lassoan — APPROVED** [review]
I haven't tested it but it looks good to me.

**Comment by jamesobutler** [comment]
On Windows/Qt 5.15/VTK 9.1/other defaults, the build process is successful.
> ========== Build: 10 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
> ========== Elapsed 38:27.271 ==========

@lassoan Are you able to merge this PR? I do not have the permissions to do so.

**Comment by lassoan** [comment]
Thank you!

**Pull request merged**
