### PR TITLE
Teev1 cameralink iactec

### PR DESCRIPTION
**Pull request by fmarcanoull**
Dear Kyle,

This pull-request corresponds to the incorporation of a new infrared sensor (Thermal Expert TE-EV1 Cameralink + DAQ grabber), as part of the IACTEC - Canarias project. The development branch is TEEV1_Cameralink_IACTEC. I'll also send pull-request for projects PlusLib, PlusApp, PlusLibData.

We will keep in touch for any observations you may suggest.

Best regards,
Fran.

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
I think that the name vtkPlusDAQUSB3FRM13BCam is not very readable.
These are just suggestions, but maybe something like vtkPlusDAQFramegraber, or vtkPlusDAQVideoSource.

**Comment by Sunderlandkyl** [comment]
It is somewhat redundant to use both VideoSource and Cam in the class name.
vtkPlusDAQVideoSource is good.

**Comment by fmarcanoull** [comment]
Name DAQUSB3FRM13BCam changed to DAQVideoSourceCam (class vtkPlusDAQVideoSourceCam, etc...). Ready to merge.

**Comment by fmarcanoull** [comment]
We prefer to keep vtkPlusDAQUSB3FRM13BCam name Is it a problem to merge the code? Also we have other requests for PlusLib, PlusApp and PlusLibData in progress. Regards.

**Comment by Sunderlandkyl** [comment]
The current name in the PR is vtkPlusDAQVideoSourceCam, which has both VideoSource and Cam. I think it is somewhat redundant to include both.

You mean that you would like to revert the device name back to vtkPlusDAQUSB3FRM13BCam?

**Comment by adamrankin** [comment]
If the device is a video feed, please have it end in VideoSource.

If this software interface is unique to the TEEV, then I recommend having that in the name.

**Comment by fmarcanoull** [comment]
I mean to keep the name vtkPlusDAQVideoSourceCam instead vtkPlusDAQVideoSource to avoid some development delay here. Please confirm if "Cam" suffix leads to confusion and it is positively recommended to rename the class to vtkPlusDAQVideoSource. Thanks!

**Comment by adamrankin** [comment]
Yes, please remove Cam from the suffix

**Comment by fmarcanoull** [comment]
I've removed the 'Cam' suffix  from DAQVideoSource in every project (PlusBuild, PlusApp, PlusLibData & PlusLib) as suggested, to continue with the review and merge. Thanks!.

**Pull request merged**
