### PR TITLE
FIX updated Atracsys cmake to align with SDK changes

### PR DESCRIPTION
**Pull request by atracsys-sbt**
Atracsys has changed its SDK inclusion via CMake. The following PR reflects these changes.
I have also changed some of the comments to be more inclusive to the fusionTrack.

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
Can you add back the PLTools path hints to FindAtracsysSDK? It is used by our build machines to compile Plus without installing SDKs.

**Comment by atracsys-sbt** [comment]
I added back the PLTools path hints.

**Comment by Sunderlandkyl** [comment]
I don't think the path hints are being used anymore. Can you update FindAtracsysSDK.cmake so that it will check for the SDK in PLTools?

**Comment by atracsys-sbt** [comment]
I'm a bit confused, in my last commit I added the path hints as you requested so that PLTools would find the SDK. I'm not sure what else I should do to facilitate the SDK check in PLTools (platform which I don't have any knowledge of).
Could you please be a bit more specific ? Thanks

**Comment by Sunderlandkyl** [comment]
In the previous version, the SDK was searched for using the path hints, to find the location of "include/ftkTypes.h":
```
find_path(ATRACSYS_SDK_DIR include/ftkTypes.h
  PATHS ${ATRACSYS_SDK_PATH_HINTS}
  DOC "Atracsys SDK directory." )
```

The desired behavior is that if we have a PLTools folder, we should check there first to set ATRACSYS_DIR, before looking for the installed SDK. Probably this can be done by adding ```${ATRACSYS_SDK_INSTALL_PATH}``` to the path hints after PLTools, and using this to set ATRACSYS_DIR:
```
find_path(ATRACSYS_DIR cmake/Atracsys/AtracsysConfig.cmake"
  PATHS ${ATRACSYS_SDK_PATH_HINTS}
  DOC "Atracsys directory." )
```

PLTools is just a version-controlled folder containing SDKs for all of the different devices that we use. I can adjust the directories to search for the SDK in PLTools, so don't worry about the exact path.

**Comment by atracsys-sbt** [comment]
Ok, it should finally work (it does on my machine). The PLtools path hints are set before checking for the installed SDK. Also, I changed the name of the cmake Atracsys variables to avoid a Warning during cmake configuration. There is a [PlusLib PR](https://github.com/PlusToolkit/PlusLib/pull/1122) related to the current PR, which should get merged simultaneously.

**Comment by Sunderlandkyl** [comment]
Thanks! I added the hints to find_package. Changes integrated in 8a693d250cf8eaaa5bb9bec76f46a995835afed2 and 709b11c06b93c68a02c791c33d28fccc90f12338.

**Pull request closed without merging**
