### PR TITLE
Intel RealSense Camera (Depth and RGB image)

### PR DESCRIPTION
**Pull request by nehk018**
We use a Intel RealSense 3d camera to send Depth and Rgb images. We use inly the Intel SDK 2.0. I know there are another RealSense Camera, but this device don't send the depth data and don't use the 2.0 version.

### CODE REVIEW

**Comment by adamrankin** [comment]
If a single camera is plugged into a computer, can both a camera and tracker Plus device access the same realsense? If not, we should merge these into a single device.

**Comment by nehk018** [comment]
I don't know. I will try tomorrow.

**Comment by lassoan** [comment]
@markasselin Please have a look at this. Make sure there is no duplicated functionality with the RealSense interface that you've developed.

**Comment by nehk018** [comment]
Hi, i'm trying to install de driver for the Intel RealSense tracker, but I don't found it. @markasselin, do you know where is the driver? Thank you.

**Comment by markasselin** [comment]
Hi Jorge, you can either install the [binaries](https://github.com/IntelRealSense/librealsense/releases) or build the drivers from source, available on Intel's [RealSense github page](https://github.com/IntelRealSense/librealsense). Ideally we'd include building these drivers as a Superbuild project in PlusBuild.

**Comment by nehk018** [comment]
Hi Mark. These drivers are the 2.0 version. The problem is that it has nor the pxcversion.h file. This is the reason that I add a new device. 

Thank you

**Comment by markasselin** [comment]
The pxcversion.h file is from a very old version of the Intel RealSense API (circa 2015). Could you describe for me the steps to test your device - especially which SDK to install and what the expected behavior should be. -M

**Comment by nehk018** [comment]
Hi Mark, I use two channels to send with openigtlink the rgb image and a depth image. So I  use the next config file to send both images:

`
<Device
      Id="VideoDevice"
      Type="IntelRealSenseCamera"
	  AcquisitionRate="27"
	  RgbDataSourceName = "VideoRGB"
	  DepthDataSourceName = "VideoDEPTH">
     <DataSources>
        <DataSource Type="Video" Id="VideoRGB" PortUsImageOrientation="UN" />
		<DataSource Type="Video" Id="VideoDEPTH" PortUsImageOrientation="UN" />
      </DataSources>
      <OutputChannels>
        <OutputChannel Id="VideoStreamRGB" VideoDataSourceId="VideoRGB" />
		<OutputChannel Id="VideoStreamDEPTH" VideoDataSourceId="VideoDEPTH" />
      </OutputChannels>
    </Device>
  </DataCollection>
`

I download the binaries and install in my computer.  In Slicer I get two images, one in RGB and other one in depth.

Thank you.

**Comment by adamrankin** [comment]
@markasselin any follow-up here?

**Comment by Sunderlandkyl** [comment]
I believe that this pull request was made obsolete by https://github.com/PlusToolkit/PlusBuild/pull/36.

**Pull request closed without merging**
