### PR TITLE
Fix build error of Qt5 not found when building VTK9

### PR DESCRIPTION
**Pull request by lassoan**
See discussion at https://github.com/PlusToolkit/PlusLib/discussions/822

This is a partial fix, because IGSIO similarly requires Qt5_DIR.

### CODE REVIEW

**Comment by adamrankin** [comment]
Do you mean if we're building VTK with Qt5, or if the user is providing a VTK with Qt enabled?

**Comment by adamrankin** [comment]
And instead of ..._BUILD_WIDGETS, maybe if Qt5_FOUND? That way if any other reason Qt is enabled, it will still work?

**Comment by lassoan** [comment]
The issue is with VTK9. It seems that if we used Qt when VTK build was configured then we need to pass Qt5_DIR to VTK again when a project uses VTK. Maybe this is fixed in latest VTK versions.

**Comment by adamrankin** [comment]
Looks good to me

**Pull request merged**
