### PR TITLE
Add MSVC80 OpenMP dll to OptiTrack 32-bit builds

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
This is the PlusBuild part of a fix to allow 32-bit versions of Plus (with OptiTrack enabled) to run successfully without having to install the MSVC redistributable.

I attached to the process in visual studio, and vcomp.dll never seemed to be loaded.
The dll could be loaded at a later time, or it could be a relic of some old dependency.
I've added both the manifest file and the dll to PLTools in any case.

https://github.com/PerkLab/PLTools/pull/3
https://github.com/PlusToolkit/PlusLib/pull/320
https://github.com/PlusToolkit/PlusBuild/pull/28

### CODE REVIEW

**Comment by adamrankin** [comment]
If the fix works, fine by me, but it isn't great practice to manually distribute MSVC dlls. If the redistributable is needed, it should be packaged with our installer and installed with the /q (I think, quiet) flag. Or we can make it a requirement for the optitrack package, and document that on the download page.

**Comment by Sunderlandkyl** [comment]
I don't think that making it a requirement for the OptiTrack package is a good idea, since it is normally enabled on most of the packages (except the Ultrasonix). It seems unreasonable to ask users to install the redistributable solely for OptiTrack support, when most will never use it.

Is there some documentation or examples on how to go about this correctly? I would much rather do it the better way if possible.

**Comment by adamrankin** [comment]
For example, when you install major software packages, games, etc... you may miss the blip that is the MSVC redist installer but it does run.

I'm not sure how to have CMake package and run another installer from NSIS, but it can be done. Here are the command line args to the various redists

> "2005 Updated\vcredist_x86.exe" /Q
> "2005 Updated\vcredist_x64.exe" /Q
> 
> "2008 SP1\vcredist_x86.exe" /qb
> "2008 SP1\vcredist_x64.exe" /qb
> 
> "2010 SP1\vcredist_x86.exe" /passive /norestart
> "2010 SP1\vcredist_x64.exe" /passive /norestart
> 
> "2012 Update 4\vcredist_x86.exe" /passive /norestart
> "2012 Update 4\vcredist_x64.exe" /passive /norestart
> 
> "2013\vcredist_x86.exe" /install /passive /norestart
> "2013\vcredist_x64.exe" /install /passive /norestart
> 
> "2015 Update 3\vc_redist.x86.exe" /install /passive /norestart
> "2015 Update 3\vc_redist.x64.exe" /install /passive /norestart
> 
> "2017\vc_redist.x86.exe" /install /passive /norestart
> "2017\vc_redist.x64.exe" /install /passive /norestart

**Comment by adamrankin** [comment]
Found this

https://cmake.org/pipermail/cmake/2006-September/011327.html

**Comment by adamrankin** [comment]
This variable also exists:
CPACK_NSIS_EXTRA_PREINSTALL_COMMANDS

**Comment by Sunderlandkyl** [comment]
Just a thought, but this method would require administrator privileges though, yes? Is this something that we would like to avoid with Plus?

**Comment by adamrankin** [comment]
Yes, it does. We do want to avoid it. Packaging the dll is fine in my opinion.

**Comment by lassoan** [comment]
Before VS2015 and Windows 8.1, Wix merge modules were the recommended way of distributing MSVCRT files, or, slightly less efficiently, using private assemblies (https://msdn.microsoft.com/en-us/library/ms235290(v=vs.90).aspx). Using redistributable package was discouraged, because these packages show up in the installed software list, users can uninstall them, breaking various applications randomly. In contrast, merge modules take care of installing files, they don't show up as separate entry in the installed software list (so users cannot uninstall them separately from your application), and files are automatically uninstalled (when all software that needed them were uninstalled).

Then, as patching MSVCRT files have become more important, Microsoft started to recommend to just install redistributable package. For me, this seemed as a temporary fix (due to issues described above), until Microsoft figured out how to solve this problem properly.  

Now MSVCRT files (universal CRT files) are considered part of the operating system and updated along with it. Applications should not bundle them, unless they target to run on pre-Windows 10 systems (https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/).

As we want to support a wide range of operating systems (from Windows XP embedded to latest Windows10) and MSVCRT versions (due to dependencies of vendor SDKs), probably the simplest method is to use private assemblies (copy all necessary files into the bin folder and add manifest files as needed). We may not benefit from security updates and package size is bigger (compared to asking the user to download&install redistributable packages separately), but I think we can live with these limitations. As we phase out old SDKs and operating systems, we may be able to retire old MSVCRT files and only use OS-provided universal CRT files.

**Comment by lassoan** [comment]
I think this should be merged.

**Pull request merged**
