### PR TITLE
Change from fork repository to opencv_contrib repo for ArUco library

### PR DESCRIPTION
**Pull request by adamrankin**
Also upgrade to OpenCV 4.2.0

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
LGTM. Does the OpticalMarkerTracker device work with this version of ArUco?

**Comment by adamrankin** [comment]
Right, testing... that's probably a good idea.

**Comment by jamesobutler** [comment]
@adamrankin Did you ever get around to testing with a newer OpenCV version?  I was looking into some OpenCV usage in Plus and notice the current OpenCV 3.4.7 is a bit out-of-date compared to the current latest (OpenCV 4.5.0).

**Comment by adamrankin** [comment]
No, it wasn't a priority, but can re-explore. I don't know if the aruco in the contrib is under it's own license

**Pull request closed without merging**
